name: ci

on:
  release:
    types:
      - created

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v2
      -
        name: Set up node environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      -
        name: Install package depdendencies
        run: yarn install
      -
        name: Run the integration tests
        run: yarn run test
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: infotition/weather-app:latest
